// const main = document.getElementsByTagName('main');
var container = document.createElement('div');
container.classList.add("container");
var cardBalance = document.createElement('div');
container.appendChild(cardBalance);
// cardBalance.classList.add("card");
var balanceTitle = document.createElement('h2');
balanceTitle.appendChild(document.createTextNode("Balance"));
cardBalance.appendChild(balanceTitle);
var tableBalance = document.createElement('table');
cardBalance.appendChild(tableBalance);
var tbody = document.createElement('tbody');
tableBalance.appendChild(tbody);
var trProfits = document.createElement('tr');
tbody.appendChild(trProfits);
var tdProfits = document.createElement('td');
trProfits.appendChild(tdProfits);
tdProfits.appendChild(document.createTextNode("Ganancias"));
var tdNumberProfits = document.createElement('td');
trProfits.appendChild(tdNumberProfits);
var spanProfit = document.createElement('span');
tdNumberProfits.appendChild(spanProfit);
var trBills = document.createElement('tr');
tbody.appendChild(trBills);
var tdBills = document.createElement('td');
trBills.appendChild(tdBills);
tdBills.appendChild(document.createTextNode("Gastos"));
var tdNumberBills = document.createElement('td');
var spanBills = document.createElement('span');
trBills.appendChild(tdNumberBills);
tdNumberBills.appendChild(spanBills);
var trSum = document.createElement('tr');
tbody.appendChild(trSum);
var tdSum = document.createElement('td');
trSum.appendChild(tdSum);
tdSum.appendChild(document.createTextNode("Total"));
var tdNumberSum = document.createElement('td');
trSum.appendChild(tdNumberSum);
var spaSum = document.createElement('span');
tdNumberSum.appendChild(spaSum);
var cardFilters = document.createElement('div');
container.appendChild(cardFilters);
var cardOperation = document.createElement('div');
container.appendChild(cardOperation);
main.appendChild(container);
